services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - ecommerce-net
    restart: unless-stopped

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - MONGO_URI=mongodb://mongo:27017/userdb
      - ORDER_SERVICE_URL=http://order-service:4003
    depends_on:
      - mongo
    networks:
      - ecommerce-net
    restart: unless-stopped

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
      - MONGO_URI=mongodb://mongo:27017/productdb
      - ORDER_SERVICE_URL=http://order-service:4003
    depends_on:
      - mongo
    networks:
      - ecommerce-net
    restart: unless-stopped

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "4003:4003"
    environment:
      - PORT=4003
      - MONGO_URI=mongodb://mongo:27017/orderdb
      - USER_SERVICE_URL=http://user-service:4001
      - PRODUCT_SERVICE_URL=http://product-service:4002
    depends_on:
      - mongo
    networks:
      - ecommerce-net
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_BASE_URL=http://mydashboardnew.duckdns.org
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - ecommerce-net
    restart: unless-stopped

networks:
  ecommerce-net:
    driver: bridge
