server {
    listen 80;

    location / {
        proxy_pass http://frontend:3000;
    }

    location /users/ {
        proxy_pass http://user-service:4001;
        rewrite ^/users/?(.*)$ /api/users/$1 break;
    }

    location /products/ {
        proxy_pass http://product-service:4002;
        rewrite ^/products/?(.*)$ /api/products/$1 break;
    }

    location /orders/ {
        proxy_pass http://order-service:4003;
        rewrite ^/orders/?(.*)$ /api/orders/$1 break;
    }
}
