server {
    listen 80;

    # Frontend
    location / {
        proxy_pass http://frontend:3000;
    }

    # API ROUTES (THIS IS THE CORE FIX)

    location /api/users {
        proxy_pass http://user-service:4001/traffic;
    }

    location /api/products {
        proxy_pass http://product-service:4002;
    }

    location /api/orders {
        proxy_pass http://order-service:4003;
    }
}
