server {
    listen 80;

    location / {
        proxy_pass http://frontend:3000;
    }

    location ~ ^/api/(users|products|orders)/traffic$ {
        default_type application/json;
        return 200 '[]';
    }

    location /api/users/ {
        proxy_pass http://user-service:4001/api/users/;
    }

    location /api/products/ {
        proxy_pass http://product-service:4002/api/products/;
    }

    location /api/orders/ {
        proxy_pass http://order-service:4003/api/orders/;
    }
}
